use_frameworks!

platform :ios, '9.0'

target 'FUScanKitSDK_Example' do
  pod 'FUScanKitSDK', :path => '../'

  target 'FUScanKitSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
