source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'FUScanKitSDK_Example' do
  pod 'FUScanKitSDK', :path => '../'

  target 'FUScanKitSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end

#bitcode disable
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
